-- 코드를 입력하세요
SELECT DISTINCT OS1.USER_ID, OS2.PRODUCT_ID
FROM ONLINE_SALE AS OS1
JOIN ONLINE_SALE AS OS2 ON OS1.USER_ID = OS2.USER_ID AND OS1.PRODUCT_ID = OS2.PRODUCT_ID
WHERE OS1.SALES_DATE != OS2.SALES_DATE
ORDER BY USER_ID ASC, PRODUCT_ID DESC;