-- 코드를 입력하세요
# SELECT AI.ANIMAL_ID, AI.NAME
# FROM ANIMAL_INS AS AI
# LEFT JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
# WHERE AO.ANIMAL_ID IS NOT NULL
# ORDER BY TIMEDIFF(AO.DATETIME, AI.DATETIME) DESC
# LIMIT 2;

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY B.DATETIME-A.DATETIME DESC
LIMIT 2