# -- 코드를 입력하세요
# SELECT U.USER_ID, U.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO,8)) AS 전화번호
# FROM USED_GOODS_BOARD AS B
# JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
# GROUP BY U.USER_ID
# HAVING COUNT(BOARD_ID) >= 3
# ORDER BY U.USER_ID DESC

SELECT DISTINCT UGU.USER_ID AS USER_ID, UGU.NICKNAME AS NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO, 4, 4), "-", SUBSTRING(TLNO, 8)) AS 전화번호
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGU.USER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY UGU.USER_ID DESC