-- 코드를 입력하세요
SELECT UGB.WRITER_ID, UGU.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(UGU.TLNO, 1,3),'-',SUBSTRING(UGU.TLNO,4,4),'-',SUBSTRING(UGU.TLNO,8)) AS TLNO
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.BOARD_ID) >= 3
ORDER BY 1 DESC;