# -- 코드를 입력하세요
# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO AS A
# LEFT JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
# WHERE A.ADDRESS LIKE '서울%'
# ORDER BY ROUND(AVG(B.REVIEW_SCORE),2) DESC, A.FAVORITES DESC;
-- 정답
SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A
JOIN REST_INFO B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING B.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, B.FAVORITES DESC