WITH RECURSIVE HOURLIST AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM HOURLIST
    WHERE HOUR < 23
)

SELECT H.HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM HOURLIST AS H
LEFT JOIN ANIMAL_OUTS AS AO ON H.HOUR = HOUR(AO.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;