-- 코드를 작성해주세요
SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO AS CHILD
JOIN ITEM_TREE AS IT ON CHILD.ITEM_ID = IT.ITEM_ID
JOIN ITEM_INFO AS PARENT ON IT.PARENT_ITEM_ID = PARENT.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY 1 DESC; 