SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (MAX_SIZE.YEAR_MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS YEAR_MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)) AS MAX_SIZE ON YEAR(E.DIFFERENTIATION_DATE) = MAX_SIZE.YEAR
ORDER BY 1, 2