SELECT FI.ID AS ID, FNI.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH > 10
    GROUP BY FISH_TYPE) AS MAX_FISH ON FI.FISH_TYPE = MAX_FISH.FISH_TYPE AND FI.LENGTH = MAX_FISH.MAX_LENGTH
ORDER BY 1 ASC